// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0--rc2
// source: swap.proto

package swap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SwapService_GetContractInfo_FullMethodName = "/swap.SwapService/GetContractInfo"
	SwapService_GetContractList_FullMethodName = "/swap.SwapService/GetContractList"
	SwapService_GetPosition_FullMethodName     = "/swap.SwapService/GetPosition"
	SwapService_GetCurrentOrder_FullMethodName = "/swap.SwapService/GetCurrentOrder"
	SwapService_GetHistoryOrder_FullMethodName = "/swap.SwapService/GetHistoryOrder"
	SwapService_GetLeverage_FullMethodName     = "/swap.SwapService/GetLeverage"
)

// SwapServiceClient is the client API for SwapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwapServiceClient interface {
	GetContractInfo(ctx context.Context, in *GetContractInfoRequest, opts ...grpc.CallOption) (*ContractInfoResponse, error)
	GetContractList(ctx context.Context, in *GetContractListRequest, opts ...grpc.CallOption) (*ContractListResponse, error)
	GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error)
	GetCurrentOrder(ctx context.Context, in *GetCurrentOrderRequest, opts ...grpc.CallOption) (*CurrentOrderResponse, error)
	GetHistoryOrder(ctx context.Context, in *GetHistoryOrderRequest, opts ...grpc.CallOption) (*HistoryOrderResponse, error)
	GetLeverage(ctx context.Context, in *GetLeverageRequest, opts ...grpc.CallOption) (*LeverageResponse, error)
}

type swapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwapServiceClient(cc grpc.ClientConnInterface) SwapServiceClient {
	return &swapServiceClient{cc}
}

func (c *swapServiceClient) GetContractInfo(ctx context.Context, in *GetContractInfoRequest, opts ...grpc.CallOption) (*ContractInfoResponse, error) {
	out := new(ContractInfoResponse)
	err := c.cc.Invoke(ctx, SwapService_GetContractInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetContractList(ctx context.Context, in *GetContractListRequest, opts ...grpc.CallOption) (*ContractListResponse, error) {
	out := new(ContractListResponse)
	err := c.cc.Invoke(ctx, SwapService_GetContractList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error) {
	out := new(PositionResponse)
	err := c.cc.Invoke(ctx, SwapService_GetPosition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetCurrentOrder(ctx context.Context, in *GetCurrentOrderRequest, opts ...grpc.CallOption) (*CurrentOrderResponse, error) {
	out := new(CurrentOrderResponse)
	err := c.cc.Invoke(ctx, SwapService_GetCurrentOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetHistoryOrder(ctx context.Context, in *GetHistoryOrderRequest, opts ...grpc.CallOption) (*HistoryOrderResponse, error) {
	out := new(HistoryOrderResponse)
	err := c.cc.Invoke(ctx, SwapService_GetHistoryOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServiceClient) GetLeverage(ctx context.Context, in *GetLeverageRequest, opts ...grpc.CallOption) (*LeverageResponse, error) {
	out := new(LeverageResponse)
	err := c.cc.Invoke(ctx, SwapService_GetLeverage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwapServiceServer is the server API for SwapService service.
// All implementations must embed UnimplementedSwapServiceServer
// for forward compatibility
type SwapServiceServer interface {
	GetContractInfo(context.Context, *GetContractInfoRequest) (*ContractInfoResponse, error)
	GetContractList(context.Context, *GetContractListRequest) (*ContractListResponse, error)
	GetPosition(context.Context, *GetPositionRequest) (*PositionResponse, error)
	GetCurrentOrder(context.Context, *GetCurrentOrderRequest) (*CurrentOrderResponse, error)
	GetHistoryOrder(context.Context, *GetHistoryOrderRequest) (*HistoryOrderResponse, error)
	GetLeverage(context.Context, *GetLeverageRequest) (*LeverageResponse, error)
	mustEmbedUnimplementedSwapServiceServer()
}

// UnimplementedSwapServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSwapServiceServer struct {
}

func (UnimplementedSwapServiceServer) GetContractInfo(context.Context, *GetContractInfoRequest) (*ContractInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractInfo not implemented")
}
func (UnimplementedSwapServiceServer) GetContractList(context.Context, *GetContractListRequest) (*ContractListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContractList not implemented")
}
func (UnimplementedSwapServiceServer) GetPosition(context.Context, *GetPositionRequest) (*PositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedSwapServiceServer) GetCurrentOrder(context.Context, *GetCurrentOrderRequest) (*CurrentOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentOrder not implemented")
}
func (UnimplementedSwapServiceServer) GetHistoryOrder(context.Context, *GetHistoryOrderRequest) (*HistoryOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoryOrder not implemented")
}
func (UnimplementedSwapServiceServer) GetLeverage(context.Context, *GetLeverageRequest) (*LeverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeverage not implemented")
}
func (UnimplementedSwapServiceServer) mustEmbedUnimplementedSwapServiceServer() {}

// UnsafeSwapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwapServiceServer will
// result in compilation errors.
type UnsafeSwapServiceServer interface {
	mustEmbedUnimplementedSwapServiceServer()
}

func RegisterSwapServiceServer(s grpc.ServiceRegistrar, srv SwapServiceServer) {
	s.RegisterService(&SwapService_ServiceDesc, srv)
}

func _SwapService_GetContractInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetContractInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetContractInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetContractInfo(ctx, req.(*GetContractInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetContractList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetContractList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetContractList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetContractList(ctx, req.(*GetContractListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetPosition(ctx, req.(*GetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetCurrentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetCurrentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetCurrentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetCurrentOrder(ctx, req.(*GetCurrentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetHistoryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetHistoryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetHistoryOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetHistoryOrder(ctx, req.(*GetHistoryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapService_GetLeverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServiceServer).GetLeverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwapService_GetLeverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServiceServer).GetLeverage(ctx, req.(*GetLeverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwapService_ServiceDesc is the grpc.ServiceDesc for SwapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swap.SwapService",
	HandlerType: (*SwapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContractInfo",
			Handler:    _SwapService_GetContractInfo_Handler,
		},
		{
			MethodName: "GetContractList",
			Handler:    _SwapService_GetContractList_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _SwapService_GetPosition_Handler,
		},
		{
			MethodName: "GetCurrentOrder",
			Handler:    _SwapService_GetCurrentOrder_Handler,
		},
		{
			MethodName: "GetHistoryOrder",
			Handler:    _SwapService_GetHistoryOrder_Handler,
		},
		{
			MethodName: "GetLeverage",
			Handler:    _SwapService_GetLeverage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swap.proto",
}

const (
	OrderEntrustService_AddOrder_FullMethodName    = "/swap.OrderEntrustService/AddOrder"
	OrderEntrustService_CancelOrder_FullMethodName = "/swap.OrderEntrustService/CancelOrder"
	OrderEntrustService_QuickClose_FullMethodName  = "/swap.OrderEntrustService/QuickClose"
)

// OrderEntrustServiceClient is the client API for OrderEntrustService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderEntrustServiceClient interface {
	AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	QuickClose(ctx context.Context, in *QuickCloseRequest, opts ...grpc.CallOption) (*QuickCloseResponse, error)
}

type orderEntrustServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderEntrustServiceClient(cc grpc.ClientConnInterface) OrderEntrustServiceClient {
	return &orderEntrustServiceClient{cc}
}

func (c *orderEntrustServiceClient) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error) {
	out := new(AddOrderResponse)
	err := c.cc.Invoke(ctx, OrderEntrustService_AddOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderEntrustServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, OrderEntrustService_CancelOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderEntrustServiceClient) QuickClose(ctx context.Context, in *QuickCloseRequest, opts ...grpc.CallOption) (*QuickCloseResponse, error) {
	out := new(QuickCloseResponse)
	err := c.cc.Invoke(ctx, OrderEntrustService_QuickClose_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderEntrustServiceServer is the server API for OrderEntrustService service.
// All implementations must embed UnimplementedOrderEntrustServiceServer
// for forward compatibility
type OrderEntrustServiceServer interface {
	AddOrder(context.Context, *AddOrderRequest) (*AddOrderResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	QuickClose(context.Context, *QuickCloseRequest) (*QuickCloseResponse, error)
	mustEmbedUnimplementedOrderEntrustServiceServer()
}

// UnimplementedOrderEntrustServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderEntrustServiceServer struct {
}

func (UnimplementedOrderEntrustServiceServer) AddOrder(context.Context, *AddOrderRequest) (*AddOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrder not implemented")
}
func (UnimplementedOrderEntrustServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderEntrustServiceServer) QuickClose(context.Context, *QuickCloseRequest) (*QuickCloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuickClose not implemented")
}
func (UnimplementedOrderEntrustServiceServer) mustEmbedUnimplementedOrderEntrustServiceServer() {}

// UnsafeOrderEntrustServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderEntrustServiceServer will
// result in compilation errors.
type UnsafeOrderEntrustServiceServer interface {
	mustEmbedUnimplementedOrderEntrustServiceServer()
}

func RegisterOrderEntrustServiceServer(s grpc.ServiceRegistrar, srv OrderEntrustServiceServer) {
	s.RegisterService(&OrderEntrustService_ServiceDesc, srv)
}

func _OrderEntrustService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEntrustServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEntrustService_AddOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEntrustServiceServer).AddOrder(ctx, req.(*AddOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderEntrustService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEntrustServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEntrustService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEntrustServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderEntrustService_QuickClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEntrustServiceServer).QuickClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEntrustService_QuickClose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEntrustServiceServer).QuickClose(ctx, req.(*QuickCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderEntrustService_ServiceDesc is the grpc.ServiceDesc for OrderEntrustService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderEntrustService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swap.OrderEntrustService",
	HandlerType: (*OrderEntrustServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrder",
			Handler:    _OrderEntrustService_AddOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderEntrustService_CancelOrder_Handler,
		},
		{
			MethodName: "QuickClose",
			Handler:    _OrderEntrustService_QuickClose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swap.proto",
}

const (
	ContractWalletService_GetWallet_FullMethodName       = "/swap.ContractWalletService/GetWallet"
	ContractWalletService_Transfer_FullMethodName        = "/swap.ContractWalletService/Transfer"
	ContractWalletService_GetTransactions_FullMethodName = "/swap.ContractWalletService/GetTransactions"
)

// ContractWalletServiceClient is the client API for ContractWalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractWalletServiceClient interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
}

type contractWalletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractWalletServiceClient(cc grpc.ClientConnInterface) ContractWalletServiceClient {
	return &contractWalletServiceClient{cc}
}

func (c *contractWalletServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, ContractWalletService_GetWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractWalletServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, ContractWalletService_Transfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractWalletServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, ContractWalletService_GetTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractWalletServiceServer is the server API for ContractWalletService service.
// All implementations must embed UnimplementedContractWalletServiceServer
// for forward compatibility
type ContractWalletServiceServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
	mustEmbedUnimplementedContractWalletServiceServer()
}

// UnimplementedContractWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContractWalletServiceServer struct {
}

func (UnimplementedContractWalletServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedContractWalletServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedContractWalletServiceServer) GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedContractWalletServiceServer) mustEmbedUnimplementedContractWalletServiceServer() {}

// UnsafeContractWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractWalletServiceServer will
// result in compilation errors.
type UnsafeContractWalletServiceServer interface {
	mustEmbedUnimplementedContractWalletServiceServer()
}

func RegisterContractWalletServiceServer(s grpc.ServiceRegistrar, srv ContractWalletServiceServer) {
	s.RegisterService(&ContractWalletService_ServiceDesc, srv)
}

func _ContractWalletService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractWalletServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractWalletService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractWalletServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractWalletService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractWalletServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractWalletService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractWalletServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractWalletService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractWalletServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractWalletService_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractWalletServiceServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractWalletService_ServiceDesc is the grpc.ServiceDesc for ContractWalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractWalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swap.ContractWalletService",
	HandlerType: (*ContractWalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _ContractWalletService_GetWallet_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _ContractWalletService_Transfer_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _ContractWalletService_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swap.proto",
}
