CREATE TABLE IF NOT EXISTS coin (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL DEFAULT '',
  can_auto_withdraw INT NOT NULL DEFAULT 0,
  can_recharge INT NOT NULL DEFAULT 1,
  can_transfer INT NOT NULL DEFAULT 1,
  can_withdraw INT NOT NULL DEFAULT 1,
  cny_rate DECIMAL(18,8) NOT NULL DEFAULT 0,
  enable_rpc INT NOT NULL DEFAULT 0,
  is_platform_coin INT NOT NULL DEFAULT 0,
  max_tx_fee DECIMAL(18,8) NOT NULL DEFAULT 0,
  max_withdraw_amount DECIMAL(32,16) NOT NULL DEFAULT 0,
  min_tx_fee DECIMAL(18,8) NOT NULL DEFAULT 0,
  min_withdraw_amount DECIMAL(32,16) NOT NULL DEFAULT 0,
  name_cn VARCHAR(64) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  status INT NOT NULL DEFAULT 1,
  unit VARCHAR(32) NOT NULL,
  usd_rate DECIMAL(18,8) NOT NULL DEFAULT 0,
  withdraw_threshold DECIMAL(32,16) NOT NULL DEFAULT 0,
  has_legal INT NOT NULL DEFAULT 0,
  cold_wallet_address VARCHAR(255) NOT NULL DEFAULT '',
  miner_fee DECIMAL(18,8) NOT NULL DEFAULT 0,
  withdraw_scale INT NOT NULL DEFAULT 8,
  account_type INT NOT NULL DEFAULT 0,
  deposit_address VARCHAR(255) NOT NULL DEFAULT '',
  infolink VARCHAR(255) NOT NULL DEFAULT '',
  information TEXT,
  min_recharge_amount DECIMAL(32,16) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_coin_unit (unit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exchange_coin (
  id BIGINT NOT NULL AUTO_INCREMENT,
  symbol VARCHAR(64) NOT NULL,
  base_coin_scale BIGINT NOT NULL DEFAULT 2,
  base_symbol VARCHAR(32) NOT NULL,
  coin_scale BIGINT NOT NULL DEFAULT 8,
  coin_symbol VARCHAR(32) NOT NULL,
  enable BIGINT NOT NULL DEFAULT 1,
  fee DECIMAL(18,8) NOT NULL DEFAULT 0,
  sort BIGINT NOT NULL DEFAULT 0,
  enable_market_buy BIGINT NOT NULL DEFAULT 1,
  enable_market_sell BIGINT NOT NULL DEFAULT 1,
  min_sell_price DECIMAL(32,16) NOT NULL DEFAULT 0,
  flag BIGINT NOT NULL DEFAULT 0,
  max_trading_order BIGINT NOT NULL DEFAULT 0,
  max_trading_time BIGINT NOT NULL DEFAULT 0,
  min_turnover DECIMAL(32,16) NOT NULL DEFAULT 0,
  clear_time BIGINT NOT NULL DEFAULT 0,
  end_time BIGINT NOT NULL DEFAULT 0,
  exchangeable BIGINT NOT NULL DEFAULT 1,
  max_buy_price DECIMAL(32,16) NOT NULL DEFAULT 0,
  max_volume DECIMAL(32,16) NOT NULL DEFAULT 0,
  min_volume DECIMAL(32,16) NOT NULL DEFAULT 0,
  publish_amount DECIMAL(32,16) NOT NULL DEFAULT 0,
  publish_price DECIMAL(32,16) NOT NULL DEFAULT 0,
  publish_type BIGINT NOT NULL DEFAULT 0,
  robot_type BIGINT NOT NULL DEFAULT 0,
  start_time BIGINT NOT NULL DEFAULT 0,
  visible BIGINT NOT NULL DEFAULT 1,
  zone BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_exchange_coin_symbol (symbol),
  KEY idx_exchange_coin_visible (visible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM exchange_coin
WHERE symbol IN ('SOL/ETH');

INSERT INTO coin (
  name,
  can_recharge,
  can_transfer,
  can_withdraw,
  name_cn,
  sort,
  status,
  unit,
  usd_rate,
  withdraw_scale,
  infolink,
  information
)
VALUES
  ('Bitcoin', 1, 1, 1, 'Bitcoin', 1, 1, 'BTC', 68000, 8, 'https://bitcoin.org', 'Local baseline coin metadata for BTC'),
  ('Tether', 1, 1, 1, 'Tether', 2, 1, 'USDT', 1, 6, 'https://tether.to', 'Local baseline coin metadata for USDT'),
  ('Ethereum', 1, 1, 1, 'Ethereum', 3, 1, 'ETH', 3200, 8, 'https://ethereum.org', 'Local baseline coin metadata for ETH'),
  ('Solana', 1, 1, 1, 'Solana', 4, 1, 'SOL', 180, 8, 'https://solana.com', 'Local baseline coin metadata for SOL')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_cn = VALUES(name_cn),
  status = VALUES(status),
  usd_rate = VALUES(usd_rate),
  withdraw_scale = VALUES(withdraw_scale),
  infolink = VALUES(infolink),
  information = VALUES(information);

INSERT INTO coin (
  name,
  can_recharge,
  can_transfer,
  can_withdraw,
  name_cn,
  sort,
  status,
  unit,
  usd_rate,
  withdraw_scale,
  infolink,
  information
)
VALUES
  ('OKB', 1, 1, 1, 'OKB', 5, 1, 'OKB', 84.06, 8, 'https://www.okx.com/okb', 'Local baseline coin metadata for OKB'),
  ('Dogecoin', 1, 1, 1, 'Dogecoin', 6, 1, 'DOGE', 0.09215, 8, 'https://dogecoin.com', 'Local baseline coin metadata for DOGE'),
  ('XRP', 1, 1, 1, 'XRP', 7, 1, 'XRP', 1.3382, 8, 'https://xrpl.org', 'Local baseline coin metadata for XRP'),
  ('Bitcoin Cash', 1, 1, 1, 'Bitcoin Cash', 8, 1, 'BCH', 438.9, 8, 'https://bch.info', 'Local baseline coin metadata for BCH'),
  ('1INCH', 1, 1, 1, '1INCH', 9, 1, '1INCH', 0.0920, 8, 'https://1inch.io', 'Local baseline coin metadata for 1INCH'),
  ('AAVE', 1, 1, 1, 'AAVE', 10, 1, 'AAVE', 90.24, 8, 'https://aave.com', 'Local baseline coin metadata for AAVE'),
  ('Alchemy Pay', 1, 1, 1, 'Alchemy Pay', 11, 1, 'ACH', 0.005837, 8, 'https://alchemypay.org', 'Local baseline coin metadata for ACH'),
  ('Cardano', 1, 1, 1, 'Cardano', 12, 1, 'ADA', 0.2501, 8, 'https://cardano.org', 'Local baseline coin metadata for ADA'),
  ('AEVO', 1, 1, 1, 'AEVO', 13, 1, 'AEVO', 0.1364, 8, 'https://www.aevo.xyz', 'Local baseline coin metadata for AEVO'),
  ('Adventure Gold', 1, 1, 1, 'Adventure Gold', 14, 1, 'AGLD', 1.48, 8, 'https://www.adventuregold.org', 'Local baseline coin metadata for AGLD'),
  ('Algorand', 1, 1, 1, 'Algorand', 15, 1, 'ALGO', 0.1672, 8, 'https://algorand.com', 'Local baseline coin metadata for ALGO'),
  ('ApeCoin', 1, 1, 1, 'ApeCoin', 16, 1, 'APE', 0.0887, 8, 'https://apecoin.com', 'Local baseline coin metadata for APE'),
  ('API3', 1, 1, 1, 'API3', 17, 1, 'API3', 0.28, 8, 'https://api3.org', 'Local baseline coin metadata for API3'),
  ('Aptos', 1, 1, 1, 'Aptos', 18, 1, 'APT', 0.8381, 8, 'https://aptoslabs.com', 'Local baseline coin metadata for APT'),
  ('Arweave', 1, 1, 1, 'Arweave', 19, 1, 'AR', 1.716, 8, 'https://www.arweave.org', 'Local baseline coin metadata for AR'),
  ('Arbitrum', 1, 1, 1, 'Arbitrum', 20, 1, 'ARB', 0.11132, 8, 'https://arbitrum.io', 'Local baseline coin metadata for ARB'),
  ('Cosmos', 1, 1, 1, 'Cosmos', 21, 1, 'ATOM', 1.821, 8, 'https://cosmos.network', 'Local baseline coin metadata for ATOM'),
  ('Binance ETH', 1, 1, 1, 'Binance ETH', 22, 1, 'BETH', 1.0008, 8, 'https://www.binance.com', 'Local baseline coin metadata for BETH'),
  ('Lido Staked ETH', 1, 1, 1, 'Lido Staked ETH', 23, 1, 'STETH', 0.9993, 8, 'https://lido.fi', 'Local baseline coin metadata for STETH')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_cn = VALUES(name_cn),
  status = VALUES(status),
  usd_rate = VALUES(usd_rate),
  withdraw_scale = VALUES(withdraw_scale),
  infolink = VALUES(infolink),
  information = VALUES(information);

INSERT INTO exchange_coin (
  symbol,
  base_coin_scale,
  base_symbol,
  coin_scale,
  coin_symbol,
  enable,
  fee,
  sort,
  enable_market_buy,
  enable_market_sell,
  exchangeable,
  visible,
  zone
)
VALUES
  ('BTC/USDT', 2, 'USDT', 4, 'BTC', 1, 0.001, 1, 1, 1, 1, 1, 0),
  ('ETH/USDT', 2, 'USDT', 4, 'ETH', 1, 0.001, 2, 1, 1, 1, 1, 0),
  ('OKB/USDT', 2, 'USDT', 4, 'OKB', 1, 0.001, 3, 1, 1, 1, 1, 0),
  ('SOL/USDT', 2, 'USDT', 4, 'SOL', 1, 0.001, 4, 1, 1, 1, 1, 0),
  ('DOGE/USDT', 4, 'USDT', 6, 'DOGE', 1, 0.001, 5, 1, 1, 1, 1, 0),
  ('XRP/USDT', 4, 'USDT', 6, 'XRP', 1, 0.001, 6, 1, 1, 1, 1, 0),
  ('BCH/USDT', 2, 'USDT', 4, 'BCH', 1, 0.001, 7, 1, 1, 1, 1, 0),
  ('1INCH/USDT', 4, 'USDT', 6, '1INCH', 1, 0.001, 8, 1, 1, 1, 1, 0),
  ('AAVE/USDT', 2, 'USDT', 4, 'AAVE', 1, 0.001, 9, 1, 1, 1, 1, 0),
  ('ACH/USDT', 4, 'USDT', 6, 'ACH', 1, 0.001, 10, 1, 1, 1, 1, 0),
  ('ADA/USDT', 4, 'USDT', 6, 'ADA', 1, 0.001, 11, 1, 1, 1, 1, 0),
  ('AEVO/USDT', 4, 'USDT', 6, 'AEVO', 1, 0.001, 12, 1, 1, 1, 1, 0),
  ('AGLD/USDT', 4, 'USDT', 6, 'AGLD', 1, 0.001, 13, 1, 1, 1, 1, 0),
  ('ALGO/USDT', 4, 'USDT', 6, 'ALGO', 1, 0.001, 14, 1, 1, 1, 1, 0),
  ('APE/USDT', 4, 'USDT', 6, 'APE', 1, 0.001, 15, 1, 1, 1, 1, 0),
  ('API3/USDT', 4, 'USDT', 6, 'API3', 1, 0.001, 16, 1, 1, 1, 1, 0),
  ('APT/USDT', 2, 'USDT', 4, 'APT', 1, 0.001, 17, 1, 1, 1, 1, 0),
  ('AR/USDT', 2, 'USDT', 4, 'AR', 1, 0.001, 18, 1, 1, 1, 1, 0),
  ('ARB/USDT', 4, 'USDT', 6, 'ARB', 1, 0.001, 19, 1, 1, 1, 1, 0),
  ('ATOM/USDT', 2, 'USDT', 4, 'ATOM', 1, 0.001, 20, 1, 1, 1, 1, 0),
  ('ETH/BTC', 8, 'BTC', 6, 'ETH', 1, 0.001, 21, 1, 1, 1, 1, 1),
  ('OKB/BTC', 8, 'BTC', 6, 'OKB', 1, 0.001, 22, 1, 1, 1, 1, 1),
  ('SOL/BTC', 8, 'BTC', 6, 'SOL', 1, 0.001, 23, 1, 1, 1, 1, 1),
  ('BETH/ETH', 8, 'ETH', 6, 'BETH', 1, 0.001, 24, 1, 1, 1, 1, 2),
  ('STETH/ETH', 8, 'ETH', 6, 'STETH', 1, 0.001, 25, 1, 1, 1, 1, 2)
ON DUPLICATE KEY UPDATE
  base_coin_scale = VALUES(base_coin_scale),
  base_symbol = VALUES(base_symbol),
  coin_scale = VALUES(coin_scale),
  coin_symbol = VALUES(coin_symbol),
  enable = VALUES(enable),
  fee = VALUES(fee),
  sort = VALUES(sort),
  enable_market_buy = VALUES(enable_market_buy),
  enable_market_sell = VALUES(enable_market_sell),
  exchangeable = VALUES(exchangeable),
  visible = VALUES(visible),
  zone = VALUES(zone);
