// Code generated by goctl. DO NOT EDIT.
package types

import "encoding/json"

// 合约信息相关
type GetContractInfoReq struct {
	Id int32 `json:"id" path:"id"`
}

type GetContractListReq struct {
}

type ContractInfoResp struct {
	Id                int32   `json:"id"`
	Symbol            string  `json:"symbol"`
	ContractType      int32   `json:"contractType"`
	PricePrecision    int32   `json:"pricePrecision"`
	QuantityPrecision int32   `json:"quantityPrecision"`
	ShareNumber       float64 `json:"shareNumber"`
	MakerFee          float64 `json:"makerFee"`
	TakerFee          float64 `json:"takerFee"`
	MinLeverage       int32   `json:"minLeverage"`
	MaxLeverage       int32   `json:"maxLeverage"`
	Status            int32   `json:"status"`
}

// 委托订单相关
type AddOrderReq struct {
	MemberId       int64   `json:"memberId"`
	ContractCoinId int32   `json:"contractCoinId"`
	EntrustType    int32   `json:"entrustType"` // 1=限价 2=市价
	Type           int32   `json:"type"`        // 1=开仓 2=平仓
	Direction      int32   `json:"direction"`   // 1=做多 2=做空
	Leverage       int32   `json:"leverage"`
	Price          float64 `json:"price"`
	Amount         float64 `json:"amount"`
	Ip             string  `json:"ip,optional"`
}

type AddOrderResp struct {
	OrderId int64 `json:"orderId"`
}

type CancelOrderReq struct {
	OrderId  int64  `json:"orderId,optional"`
	MemberId int64  `json:"memberId,optional"`
	Ip       string `json:"ip,optional"`
}

type CancelOrderResp struct {
	Success bool `json:"success"`
}

type CurrentOrderReq struct {
	MemberId       int64 `json:"memberId"`
	PageNo         int   `json:"pageNo,optional"`
	PageSize       int   `json:"pageSize,optional"`
	ContractCoinId int32 `json:"contractCoinId,optional"`
	Type           int32 `json:"type,optional"`
	Ip             string `json:"ip,optional"`
}

type HistoryOrderReq struct {
	MemberId       int64 `json:"memberId"`
	PageNo         int   `json:"pageNo,optional"`
	PageSize       int   `json:"pageSize,optional"`
	ContractCoinId int32 `json:"contractCoinId,optional"`
	Type           int32 `json:"type,optional"`
	Ip             string `json:"ip,optional"`
}

type OrderInfo struct {
	Id             int64   `json:"id"`
	MemberId       int64   `json:"memberId"`
	ContractCoinId int32   `json:"contractCoinId"`
	EntrustType    int32   `json:"entrustType"`
	Type           int32   `json:"type"`
	Direction      int32   `json:"direction"`
	Leverage       int32   `json:"leverage"`
	Price          float64 `json:"price"`
	Amount         float64 `json:"amount"`
	Status         int32   `json:"status"`
	CreateTime     string  `json:"createTime"`
}

type CurrentOrderResp struct {
	List          []*UcOrderItem `json:"list"`
	Content       []*UcOrderItem `json:"content"`
	TotalElements int64          `json:"totalElements"`
	Number        int64          `json:"number"`
	TotalPages    int64          `json:"totalPages"`
	HasNext       bool           `json:"hasNext"`
	IsLast        bool           `json:"isLast"`
}

type HistoryOrderResp struct {
	List          []*UcOrderItem `json:"list"`
	Content       []*UcOrderItem `json:"content"`
	TotalElements int64          `json:"totalElements"`
	Number        int64          `json:"number"`
	TotalPages    int64          `json:"totalPages"`
	HasNext       bool           `json:"hasNext"`
	IsLast        bool           `json:"isLast"`
}

type UcOrderItem struct {
	OrderId          int64   `json:"id"`
	ContractCoinId   int64   `json:"contractCoinId"`
	ContractCoinName string  `json:"contractCoinName"`
	ContractCoinType string  `json:"contractCoinType"`
	HoldTime         int32   `json:"holdTime"`
	Direction        string  `json:"direction"`
	EntrustType      string  `json:"entrustType"`
	Type             string  `json:"type"`
	Leverage         int32   `json:"leverage"`
	EntrustPrice     float64 `json:"entrustPrice"`
	StrikePrice      float64 `json:"strikePrice"`
	TriggerPrice     float64 `json:"triggerPrice"`
	Share            float64 `json:"share"`
	PrincipalAmount  float64 `json:"principalAmount"`
	Fee              float64 `json:"fee"`
	Profit           float64 `json:"profit"`
	Status           string  `json:"status"`
	CreateTime       string  `json:"createTime"`
}

// 持仓相关
type PositionReq struct {
	MemberId       int64 `json:"memberId"`
	ContractCoinId int32 `json:"contractCoinId,optional"`
	Ip             string `json:"ip,optional"`
}

type PositionInfo struct {
	Id               int64   `json:"id"`
	MemberId         int64   `json:"memberId"`
	ContractCoinId   int32   `json:"contractCoinId"`
	Direction        int32   `json:"direction"`
	Leverage         int32   `json:"leverage"`
	Size             float64 `json:"size"`
	EntryPrice       float64 `json:"entryPrice"`
	Margin           float64 `json:"margin"`
	UnrealizedPnl    float64 `json:"unrealizedPnl"`
	LiquidationPrice float64 `json:"liquidationPrice"`
}

type PositionResp struct {
	List []*SwapPositionItem `json:"list"`
}

type SwapPositionItem struct {
	Id               int64   `json:"id"`
	ContractCoinId   int64   `json:"contractCoinId"`
	ContractCoinName string  `json:"contractCoinName"`
	ContractCoinType string  `json:"contractCoinType"`
	HoldTime         int32   `json:"holdTime"`
	Direction        string  `json:"direction"`
	Multiple         int32   `json:"multiple"`
	OpenPrice        float64 `json:"openPrice"`
	PrincipalAmount  float64 `json:"principalAmount"`
	Position         float64 `json:"position"`
	AvailablePosition float64 `json:"availablePosition"`
	LiquidationPrice float64 `json:"liquidationPrice"`
	Profit           float64 `json:"profit"`
}

// 闪电平仓
type QuickCloseReq struct {
	MemberId       int64   `json:"memberId"`
	ContractCoinId int32   `json:"contractCoinId"`
	Price          float64 `json:"price,optional"`
	Ip             string  `json:"ip,optional"`
}

type QuickCloseResp struct {
	Success bool `json:"success"`
}

// 杠杆
type LeverageReq struct {
	MemberId       int64 `json:"memberId"`
	ContractCoinId int32 `json:"contractCoinId"`
	Ip             string `json:"ip,optional"`
}

type LeverageResp struct {
	Leverage int32 `json:"leverage"`
}

// 合约钱包相关
type ContractWalletReq struct {
	MemberId int64  `json:"memberId"`
	Unit     string `json:"unit,optional"`
	Ip       string `json:"ip,optional"`
}

type ContractWalletResp struct {
	Balance       float64 `json:"balance"`
	FrozenBalance float64 `json:"frozenBalance"`
	Available     float64 `json:"available"`
	Unit          string  `json:"unit"`
}

type WalletCoinItem struct {
	Unit    string  `json:"unit"`
	Name    string  `json:"name"`
	UsdRate float64 `json:"usdRate"`
	CnyRate float64 `json:"cnyRate"`
}

type ContractWalletItem struct {
	Coin          *WalletCoinItem `json:"coin"`
	Balance       float64         `json:"balance"`
	FrozenBalance float64         `json:"frozenBalance"`
	ToReleased    float64         `json:"toReleased"`
	MainBalance   float64         `json:"mainBalance"`
}

type ContractTransferReq struct {
	MemberId  int64   `json:"memberId"`
	Unit      string  `json:"unit"`
	Amount    float64 `json:"amount"`
	Type      int32   `json:"type"` // 1=转入 2=转出
	Direction int32   `json:"direction,optional"`
	Ip        string  `json:"ip,optional"`
}

type ContractTransferResp struct {
	Success bool `json:"success"`
}

type ContractTransactionReq struct {
	MemberId  int64  `json:"memberId"`
	PageNo    int    `json:"pageNo,optional"`
	PageSize  int    `json:"pageSize,optional"`
	Symbol    string `json:"symbol,optional"`
	StartTime string `json:"startTime,optional"`
	EndTime   string `json:"endTime,optional"`
	Type      json.RawMessage `json:"type,optional"`
	Ip        string `json:"ip,optional"`
}

type TransactionInfo struct {
	Id             int64   `json:"id"`
	MemberId       int64   `json:"memberId"`
	Unit           string  `json:"unit"`
	Type           int32   `json:"type"`
	Amount         float64 `json:"amount"`
	Balance        float64 `json:"balance"`
	CreateTime     string  `json:"createTime"`
	Remark         string  `json:"remark"`
	RelatedOrderId int64   `json:"relatedOrderId"`
}

type ContractTransactionResp struct {
	List  []*TransactionInfo `json:"list"`
	Total int                `json:"total"`
}

type ContractTransactionItem struct {
	CreateTime string  `json:"createTime"`
	Type       int32   `json:"type"`
	Symbol     string  `json:"symbol"`
	Amount     float64 `json:"amount"`
}

type ContractCoinThumbItem struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// K 线历史相关 (用于 TradingView)
type HistoryKlineReq struct {
	Symbol     string `json:"symbol"`
	From       int64  `json:"from"` // 开始时间戳 (毫秒)
	To         int64  `json:"to"`   // 结束时间戳 (毫秒)
	Resolution string `json:"resolution"` // 分辨率：1, 5, 15, 30, 60, 1D, 1W, 1M
}

type HistoryKlineResp struct {
	List [][]any `json:"list"` // [[time, open, high, low, close, volume], ...]
}
