// Code generated by goctl. DO NOT EDIT.
// Source: swap.proto

package server

import (
	"context"
	"swap/internal/logic"
	"swap/internal/svc"
	"swap/types/swap"
)

type ContractWalletServiceServer struct {
	svcCtx *svc.ServiceContext
	swap.UnimplementedContractWalletServiceServer
}

func (s *ContractWalletServiceServer) GetWallet(ctx context.Context, req *swap.GetWalletRequest) (*swap.GetWalletResponse, error) {
	l := logic.NewContractWalletLogic(ctx, s.svcCtx)
	return l.GetWallet(req)
}

func (s *ContractWalletServiceServer) Transfer(ctx context.Context, req *swap.TransferRequest) (*swap.TransferResponse, error) {
	l := logic.NewContractWalletLogic(ctx, s.svcCtx)
	return l.Transfer(req)
}

func (s *ContractWalletServiceServer) GetTransactions(ctx context.Context, req *swap.GetTransactionsRequest) (*swap.GetTransactionsResponse, error) {
	l := logic.NewContractWalletLogic(ctx, s.svcCtx)
	return l.GetTransactions(req)
}

func NewContractWalletServiceServer(svcCtx *svc.ServiceContext) *ContractWalletServiceServer {
	return &ContractWalletServiceServer{
		svcCtx: svcCtx,
	}
}
