// Code generated by goctl. DO NOT EDIT.
// Source: swap.proto

package server

import (
	"context"
	"swap/internal/logic"
	"swap/internal/svc"
	"swap/types/swap"
)

type OrderEntrustServiceServer struct {
	svcCtx *svc.ServiceContext
	swap.UnimplementedOrderEntrustServiceServer
}

func (s *OrderEntrustServiceServer) AddOrder(ctx context.Context, req *swap.AddOrderRequest) (*swap.AddOrderResponse, error) {
	l := logic.NewOrderEntrustLogic(ctx, s.svcCtx)
	return l.AddOrder(req)
}

func (s *OrderEntrustServiceServer) CancelOrder(ctx context.Context, req *swap.CancelOrderRequest) (*swap.CancelOrderResponse, error) {
	l := logic.NewOrderEntrustLogic(ctx, s.svcCtx)
	return l.CancelOrder(req)
}

func (s *OrderEntrustServiceServer) QuickClose(ctx context.Context, req *swap.QuickCloseRequest) (*swap.QuickCloseResponse, error) {
	l := logic.NewOrderEntrustLogic(ctx, s.svcCtx)
	return l.QuickClose(req)
}

func NewOrderEntrustServiceServer(svcCtx *svc.ServiceContext) *OrderEntrustServiceServer {
	return &OrderEntrustServiceServer{
		svcCtx: svcCtx,
	}
}
