// Code generated by goctl. DO NOT EDIT.
// Source: swap.proto

package server

import (
	"context"
	"swap/internal/logic"
	"swap/internal/svc"
	"swap/types/swap"
)

type SwapServiceServer struct {
	svcCtx *svc.ServiceContext
	swap.UnimplementedSwapServiceServer
}

func (s *SwapServiceServer) GetContractInfo(ctx context.Context, req *swap.GetContractInfoRequest) (*swap.ContractInfoResponse, error) {
	l := logic.NewContractInfoLogic(ctx, s.svcCtx)
	return l.GetContractInfo(req)
}

func (s *SwapServiceServer) GetContractList(ctx context.Context, req *swap.GetContractListRequest) (*swap.ContractListResponse, error) {
	l := logic.NewContractInfoLogic(ctx, s.svcCtx)
	return l.GetContractList(req)
}

func (s *SwapServiceServer) GetPosition(ctx context.Context, req *swap.GetPositionRequest) (*swap.PositionResponse, error) {
	l := logic.NewPositionLogic(ctx, s.svcCtx)
	return l.GetPosition(req)
}

func (s *SwapServiceServer) GetCurrentOrder(ctx context.Context, req *swap.GetCurrentOrderRequest) (*swap.CurrentOrderResponse, error) {
	l := logic.NewPositionLogic(ctx, s.svcCtx)
	return l.GetCurrentOrder(req)
}

func (s *SwapServiceServer) GetHistoryOrder(ctx context.Context, req *swap.GetHistoryOrderRequest) (*swap.HistoryOrderResponse, error) {
	l := logic.NewPositionLogic(ctx, s.svcCtx)
	return l.GetHistoryOrder(req)
}

func (s *SwapServiceServer) GetLeverage(ctx context.Context, req *swap.GetLeverageRequest) (*swap.LeverageResponse, error) {
	l := logic.NewPositionLogic(ctx, s.svcCtx)
	return l.GetLeverage(req)
}

func NewSwapServiceServer(svcCtx *svc.ServiceContext) *SwapServiceServer {
	return &SwapServiceServer{
		svcCtx: svcCtx,
	}
}
