// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: swap.proto

package swap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取合约信息请求
type GetContractInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractInfoRequest) Reset() {
	*x = GetContractInfoRequest{}
	mi := &file_swap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractInfoRequest) ProtoMessage() {}

func (x *GetContractInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractInfoRequest.ProtoReflect.Descriptor instead.
func (*GetContractInfoRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{0}
}

func (x *GetContractInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 合约信息响应
type ContractInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ContractType      int32                  `protobuf:"varint,3,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
	PricePrecision    int32                  `protobuf:"varint,4,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	QuantityPrecision int32                  `protobuf:"varint,5,opt,name=quantity_precision,json=quantityPrecision,proto3" json:"quantity_precision,omitempty"`
	ShareNumber       float64                `protobuf:"fixed64,6,opt,name=share_number,json=shareNumber,proto3" json:"share_number,omitempty"`
	MakerFee          float64                `protobuf:"fixed64,7,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerFee          float64                `protobuf:"fixed64,8,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	MinLeverage       int32                  `protobuf:"varint,9,opt,name=min_leverage,json=minLeverage,proto3" json:"min_leverage,omitempty"`
	MaxLeverage       int32                  `protobuf:"varint,10,opt,name=max_leverage,json=maxLeverage,proto3" json:"max_leverage,omitempty"`
	Status            int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContractInfoResponse) Reset() {
	*x = ContractInfoResponse{}
	mi := &file_swap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractInfoResponse) ProtoMessage() {}

func (x *ContractInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractInfoResponse.ProtoReflect.Descriptor instead.
func (*ContractInfoResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{1}
}

func (x *ContractInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContractInfoResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ContractInfoResponse) GetContractType() int32 {
	if x != nil {
		return x.ContractType
	}
	return 0
}

func (x *ContractInfoResponse) GetPricePrecision() int32 {
	if x != nil {
		return x.PricePrecision
	}
	return 0
}

func (x *ContractInfoResponse) GetQuantityPrecision() int32 {
	if x != nil {
		return x.QuantityPrecision
	}
	return 0
}

func (x *ContractInfoResponse) GetShareNumber() float64 {
	if x != nil {
		return x.ShareNumber
	}
	return 0
}

func (x *ContractInfoResponse) GetMakerFee() float64 {
	if x != nil {
		return x.MakerFee
	}
	return 0
}

func (x *ContractInfoResponse) GetTakerFee() float64 {
	if x != nil {
		return x.TakerFee
	}
	return 0
}

func (x *ContractInfoResponse) GetMinLeverage() int32 {
	if x != nil {
		return x.MinLeverage
	}
	return 0
}

func (x *ContractInfoResponse) GetMaxLeverage() int32 {
	if x != nil {
		return x.MaxLeverage
	}
	return 0
}

func (x *ContractInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 获取合约列表请求
type GetContractListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractListRequest) Reset() {
	*x = GetContractListRequest{}
	mi := &file_swap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractListRequest) ProtoMessage() {}

func (x *GetContractListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractListRequest.ProtoReflect.Descriptor instead.
func (*GetContractListRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{2}
}

// 合约列表响应
type ContractListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	List          []*ContractInfoResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractListResponse) Reset() {
	*x = ContractListResponse{}
	mi := &file_swap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractListResponse) ProtoMessage() {}

func (x *ContractListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractListResponse.ProtoReflect.Descriptor instead.
func (*ContractListResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{3}
}

func (x *ContractListResponse) GetList() []*ContractInfoResponse {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取持仓请求
type GetPositionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,2,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_swap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{4}
}

func (x *GetPositionRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetPositionRequest) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

// 持仓信息
type PositionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId         int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId   int32                  `protobuf:"varint,3,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	Direction        int32                  `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Leverage         int32                  `protobuf:"varint,5,opt,name=leverage,proto3" json:"leverage,omitempty"`
	Size             float64                `protobuf:"fixed64,6,opt,name=size,proto3" json:"size,omitempty"`
	EntryPrice       float64                `protobuf:"fixed64,7,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	Margin           float64                `protobuf:"fixed64,8,opt,name=margin,proto3" json:"margin,omitempty"`
	UnrealizedPnl    float64                `protobuf:"fixed64,9,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	LiquidationPrice float64                `protobuf:"fixed64,10,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PositionInfo) Reset() {
	*x = PositionInfo{}
	mi := &file_swap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfo) ProtoMessage() {}

func (x *PositionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfo.ProtoReflect.Descriptor instead.
func (*PositionInfo) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{5}
}

func (x *PositionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionInfo) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *PositionInfo) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

func (x *PositionInfo) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *PositionInfo) GetLeverage() int32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *PositionInfo) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PositionInfo) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *PositionInfo) GetMargin() float64 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *PositionInfo) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *PositionInfo) GetLiquidationPrice() float64 {
	if x != nil {
		return x.LiquidationPrice
	}
	return 0
}

// 持仓响应
type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PositionInfo        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_swap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{6}
}

func (x *PositionResponse) GetList() []*PositionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取当前委托请求
type GetCurrentOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,2,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCurrentOrderRequest) Reset() {
	*x = GetCurrentOrderRequest{}
	mi := &file_swap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentOrderRequest) ProtoMessage() {}

func (x *GetCurrentOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentOrderRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentOrderRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{7}
}

func (x *GetCurrentOrderRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetCurrentOrderRequest) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

// 委托信息
type OrderInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId       int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,3,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	EntrustType    int32                  `protobuf:"varint,4,opt,name=entrust_type,json=entrustType,proto3" json:"entrust_type,omitempty"`
	Type           int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Direction      int32                  `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Leverage       int32                  `protobuf:"varint,7,opt,name=leverage,proto3" json:"leverage,omitempty"`
	Price          float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Amount         float64                `protobuf:"fixed64,9,opt,name=amount,proto3" json:"amount,omitempty"`
	DealAmount     float64                `protobuf:"fixed64,10,opt,name=deal_amount,json=dealAmount,proto3" json:"deal_amount,omitempty"`
	Status         int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	DealAmountUsdt float64                `protobuf:"fixed64,12,opt,name=deal_amount_usdt,json=dealAmountUsdt,proto3" json:"deal_amount_usdt,omitempty"`
	Fee            float64                `protobuf:"fixed64,13,opt,name=fee,proto3" json:"fee,omitempty"`
	FeeUnit        string                 `protobuf:"bytes,14,opt,name=fee_unit,json=feeUnit,proto3" json:"fee_unit,omitempty"`
	Profit         float64                `protobuf:"fixed64,15,opt,name=profit,proto3" json:"profit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_swap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{8}
}

func (x *OrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *OrderInfo) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

func (x *OrderInfo) GetEntrustType() int32 {
	if x != nil {
		return x.EntrustType
	}
	return 0
}

func (x *OrderInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *OrderInfo) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *OrderInfo) GetLeverage() int32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *OrderInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderInfo) GetDealAmount() float64 {
	if x != nil {
		return x.DealAmount
	}
	return 0
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetDealAmountUsdt() float64 {
	if x != nil {
		return x.DealAmountUsdt
	}
	return 0
}

func (x *OrderInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *OrderInfo) GetFeeUnit() string {
	if x != nil {
		return x.FeeUnit
	}
	return ""
}

func (x *OrderInfo) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

// 当前委托响应
type CurrentOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentOrderResponse) Reset() {
	*x = CurrentOrderResponse{}
	mi := &file_swap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentOrderResponse) ProtoMessage() {}

func (x *CurrentOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentOrderResponse.ProtoReflect.Descriptor instead.
func (*CurrentOrderResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{9}
}

func (x *CurrentOrderResponse) GetList() []*OrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取历史委托请求
type GetHistoryOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,2,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	StartTime      int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryOrderRequest) Reset() {
	*x = GetHistoryOrderRequest{}
	mi := &file_swap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryOrderRequest) ProtoMessage() {}

func (x *GetHistoryOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryOrderRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryOrderRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryOrderRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetHistoryOrderRequest) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

func (x *GetHistoryOrderRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetHistoryOrderRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 历史委托响应
type HistoryOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOrderResponse) Reset() {
	*x = HistoryOrderResponse{}
	mi := &file_swap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOrderResponse) ProtoMessage() {}

func (x *HistoryOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOrderResponse.ProtoReflect.Descriptor instead.
func (*HistoryOrderResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{11}
}

func (x *HistoryOrderResponse) GetList() []*OrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取杠杆设置请求
type GetLeverageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,2,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLeverageRequest) Reset() {
	*x = GetLeverageRequest{}
	mi := &file_swap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeverageRequest) ProtoMessage() {}

func (x *GetLeverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeverageRequest.ProtoReflect.Descriptor instead.
func (*GetLeverageRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{12}
}

func (x *GetLeverageRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetLeverageRequest) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

// 杠杆响应
type LeverageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leverage      int32                  `protobuf:"varint,1,opt,name=leverage,proto3" json:"leverage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeverageResponse) Reset() {
	*x = LeverageResponse{}
	mi := &file_swap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeverageResponse) ProtoMessage() {}

func (x *LeverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeverageResponse.ProtoReflect.Descriptor instead.
func (*LeverageResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{13}
}

func (x *LeverageResponse) GetLeverage() int32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

// 添加委托请求
type AddOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,2,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	EntrustType    int32                  `protobuf:"varint,3,opt,name=entrust_type,json=entrustType,proto3" json:"entrust_type,omitempty"`
	Type           int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Direction      int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Leverage       int32                  `protobuf:"varint,6,opt,name=leverage,proto3" json:"leverage,omitempty"`
	Price          float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Amount         float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_swap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{14}
}

func (x *AddOrderRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AddOrderRequest) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

func (x *AddOrderRequest) GetEntrustType() int32 {
	if x != nil {
		return x.EntrustType
	}
	return 0
}

func (x *AddOrderRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AddOrderRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *AddOrderRequest) GetLeverage() int32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *AddOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 添加委托响应
type AddOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderResponse) Reset() {
	*x = AddOrderResponse{}
	mi := &file_swap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderResponse) ProtoMessage() {}

func (x *AddOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderResponse.ProtoReflect.Descriptor instead.
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{15}
}

func (x *AddOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// 撤销委托请求
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MemberId      int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_swap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{16}
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

// 撤销委托响应
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_swap_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{17}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 闪电平仓请求
type QuickCloseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PositionId     int64                  `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	MemberId       int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ContractCoinId int32                  `protobuf:"varint,3,opt,name=contract_coin_id,json=contractCoinId,proto3" json:"contract_coin_id,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuickCloseRequest) Reset() {
	*x = QuickCloseRequest{}
	mi := &file_swap_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickCloseRequest) ProtoMessage() {}

func (x *QuickCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickCloseRequest.ProtoReflect.Descriptor instead.
func (*QuickCloseRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{18}
}

func (x *QuickCloseRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *QuickCloseRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *QuickCloseRequest) GetContractCoinId() int32 {
	if x != nil {
		return x.ContractCoinId
	}
	return 0
}

func (x *QuickCloseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// 闪电平仓响应
type QuickCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickCloseResponse) Reset() {
	*x = QuickCloseResponse{}
	mi := &file_swap_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickCloseResponse) ProtoMessage() {}

func (x *QuickCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickCloseResponse.ProtoReflect.Descriptor instead.
func (*QuickCloseResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{19}
}

func (x *QuickCloseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取钱包请求
type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_swap_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{20}
}

func (x *GetWalletRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetWalletRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// 钱包信息
type WalletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Frozen        float64                `protobuf:"fixed64,5,opt,name=frozen,proto3" json:"frozen,omitempty"`
	MainBalance   float64                `protobuf:"fixed64,6,opt,name=main_balance,json=mainBalance,proto3" json:"main_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletInfo) Reset() {
	*x = WalletInfo{}
	mi := &file_swap_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfo) ProtoMessage() {}

func (x *WalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfo.ProtoReflect.Descriptor instead.
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{21}
}

func (x *WalletInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WalletInfo) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *WalletInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *WalletInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WalletInfo) GetFrozen() float64 {
	if x != nil {
		return x.Frozen
	}
	return 0
}

func (x *WalletInfo) GetMainBalance() float64 {
	if x != nil {
		return x.MainBalance
	}
	return 0
}

// 钱包响应
type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletInfo            `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_swap_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{22}
}

func (x *GetWalletResponse) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// 资金划转请求
type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Direction     int32                  `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_swap_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{23}
}

func (x *TransferRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *TransferRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// 资金划转响应
type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_swap_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{24}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取合约账单请求
type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_swap_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{25}
}

func (x *GetTransactionsRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetTransactionsRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetTransactionsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetTransactionsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetTransactionsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 账单信息
type TransactionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId       int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Unit           string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Type           int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Amount         float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance        float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	RelatedOrderId int64                  `protobuf:"varint,7,opt,name=related_order_id,json=relatedOrderId,proto3" json:"related_order_id,omitempty"`
	Remark         string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_swap_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{26}
}

func (x *TransactionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionInfo) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *TransactionInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TransactionInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TransactionInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *TransactionInfo) GetRelatedOrderId() int64 {
	if x != nil {
		return x.RelatedOrderId
	}
	return 0
}

func (x *TransactionInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 合约账单响应
type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TransactionInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_swap_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swap_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_swap_proto_rawDescGZIP(), []int{27}
}

func (x *GetTransactionsResponse) GetList() []*TransactionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_swap_proto protoreflect.FileDescriptor

const file_swap_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"swap.proto\x12\x04swap\"(\n" +
	"\x16GetContractInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xf6\x02\n" +
	"\x14ContractInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12#\n" +
	"\rcontract_type\x18\x03 \x01(\x05R\fcontractType\x12'\n" +
	"\x0fprice_precision\x18\x04 \x01(\x05R\x0epricePrecision\x12-\n" +
	"\x12quantity_precision\x18\x05 \x01(\x05R\x11quantityPrecision\x12!\n" +
	"\fshare_number\x18\x06 \x01(\x01R\vshareNumber\x12\x1b\n" +
	"\tmaker_fee\x18\a \x01(\x01R\bmakerFee\x12\x1b\n" +
	"\ttaker_fee\x18\b \x01(\x01R\btakerFee\x12!\n" +
	"\fmin_leverage\x18\t \x01(\x05R\vminLeverage\x12!\n" +
	"\fmax_leverage\x18\n" +
	" \x01(\x05R\vmaxLeverage\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\"\x18\n" +
	"\x16GetContractListRequest\"F\n" +
	"\x14ContractListResponse\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.swap.ContractInfoResponseR\x04list\"[\n" +
	"\x12GetPositionRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x02 \x01(\x05R\x0econtractCoinId\"\xc0\x02\n" +
	"\fPositionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x03 \x01(\x05R\x0econtractCoinId\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\x12\x1a\n" +
	"\bleverage\x18\x05 \x01(\x05R\bleverage\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x01R\x04size\x12\x1f\n" +
	"\ventry_price\x18\a \x01(\x01R\n" +
	"entryPrice\x12\x16\n" +
	"\x06margin\x18\b \x01(\x01R\x06margin\x12%\n" +
	"\x0eunrealized_pnl\x18\t \x01(\x01R\runrealizedPnl\x12+\n" +
	"\x11liquidation_price\x18\n" +
	" \x01(\x01R\x10liquidationPrice\":\n" +
	"\x10PositionResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.swap.PositionInfoR\x04list\"_\n" +
	"\x16GetCurrentOrderRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x02 \x01(\x05R\x0econtractCoinId\"\xa9\x03\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x03 \x01(\x05R\x0econtractCoinId\x12!\n" +
	"\fentrust_type\x18\x04 \x01(\x05R\ventrustType\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\x05R\tdirection\x12\x1a\n" +
	"\bleverage\x18\a \x01(\x05R\bleverage\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x16\n" +
	"\x06amount\x18\t \x01(\x01R\x06amount\x12\x1f\n" +
	"\vdeal_amount\x18\n" +
	" \x01(\x01R\n" +
	"dealAmount\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12(\n" +
	"\x10deal_amount_usdt\x18\f \x01(\x01R\x0edealAmountUsdt\x12\x10\n" +
	"\x03fee\x18\r \x01(\x01R\x03fee\x12\x19\n" +
	"\bfee_unit\x18\x0e \x01(\tR\afeeUnit\x12\x16\n" +
	"\x06profit\x18\x0f \x01(\x01R\x06profit\";\n" +
	"\x14CurrentOrderResponse\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.swap.OrderInfoR\x04list\"\x99\x01\n" +
	"\x16GetHistoryOrderRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x02 \x01(\x05R\x0econtractCoinId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\";\n" +
	"\x14HistoryOrderResponse\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.swap.OrderInfoR\x04list\"[\n" +
	"\x12GetLeverageRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x02 \x01(\x05R\x0econtractCoinId\".\n" +
	"\x10LeverageResponse\x12\x1a\n" +
	"\bleverage\x18\x01 \x01(\x05R\bleverage\"\xf7\x01\n" +
	"\x0fAddOrderRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x02 \x01(\x05R\x0econtractCoinId\x12!\n" +
	"\fentrust_type\x18\x03 \x01(\x05R\ventrustType\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x1a\n" +
	"\bleverage\x18\x06 \x01(\x05R\bleverage\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\"-\n" +
	"\x10AddOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"L\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\"/\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x11QuickCloseRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x03R\n" +
	"positionId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12(\n" +
	"\x10contract_coin_id\x18\x03 \x01(\x05R\x0econtractCoinId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\".\n" +
	"\x12QuickCloseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\"\xa2\x01\n" +
	"\n" +
	"WalletInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12\x16\n" +
	"\x06frozen\x18\x05 \x01(\x01R\x06frozen\x12!\n" +
	"\fmain_balance\x18\x06 \x01(\x01R\vmainBalance\"=\n" +
	"\x11GetWalletResponse\x12(\n" +
	"\x06wallet\x18\x01 \x01(\v2\x10.swap.WalletInfoR\x06wallet\"x\n" +
	"\x0fTransferRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\",\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x97\x01\n" +
	"\x16GetTransactionsRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\"\xda\x01\n" +
	"\x0fTransactionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12(\n" +
	"\x10related_order_id\x18\a \x01(\x03R\x0erelatedOrderId\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\"D\n" +
	"\x17GetTransactionsResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.swap.TransactionInfoR\x04list2\xc3\x03\n" +
	"\vSwapService\x12K\n" +
	"\x0fGetContractInfo\x12\x1c.swap.GetContractInfoRequest\x1a\x1a.swap.ContractInfoResponse\x12K\n" +
	"\x0fGetContractList\x12\x1c.swap.GetContractListRequest\x1a\x1a.swap.ContractListResponse\x12?\n" +
	"\vGetPosition\x12\x18.swap.GetPositionRequest\x1a\x16.swap.PositionResponse\x12K\n" +
	"\x0fGetCurrentOrder\x12\x1c.swap.GetCurrentOrderRequest\x1a\x1a.swap.CurrentOrderResponse\x12K\n" +
	"\x0fGetHistoryOrder\x12\x1c.swap.GetHistoryOrderRequest\x1a\x1a.swap.HistoryOrderResponse\x12?\n" +
	"\vGetLeverage\x12\x18.swap.GetLeverageRequest\x1a\x16.swap.LeverageResponse2\xd5\x01\n" +
	"\x13OrderEntrustService\x129\n" +
	"\bAddOrder\x12\x15.swap.AddOrderRequest\x1a\x16.swap.AddOrderResponse\x12B\n" +
	"\vCancelOrder\x12\x18.swap.CancelOrderRequest\x1a\x19.swap.CancelOrderResponse\x12?\n" +
	"\n" +
	"QuickClose\x12\x17.swap.QuickCloseRequest\x1a\x18.swap.QuickCloseResponse2\xe0\x01\n" +
	"\x15ContractWalletService\x12<\n" +
	"\tGetWallet\x12\x16.swap.GetWalletRequest\x1a\x17.swap.GetWalletResponse\x129\n" +
	"\bTransfer\x12\x15.swap.TransferRequest\x1a\x16.swap.TransferResponse\x12N\n" +
	"\x0fGetTransactions\x12\x1c.swap.GetTransactionsRequest\x1a\x1d.swap.GetTransactionsResponseB\bZ\x06./swapb\x06proto3"

var (
	file_swap_proto_rawDescOnce sync.Once
	file_swap_proto_rawDescData []byte
)

func file_swap_proto_rawDescGZIP() []byte {
	file_swap_proto_rawDescOnce.Do(func() {
		file_swap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swap_proto_rawDesc), len(file_swap_proto_rawDesc)))
	})
	return file_swap_proto_rawDescData
}

var file_swap_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_swap_proto_goTypes = []any{
	(*GetContractInfoRequest)(nil),  // 0: swap.GetContractInfoRequest
	(*ContractInfoResponse)(nil),    // 1: swap.ContractInfoResponse
	(*GetContractListRequest)(nil),  // 2: swap.GetContractListRequest
	(*ContractListResponse)(nil),    // 3: swap.ContractListResponse
	(*GetPositionRequest)(nil),      // 4: swap.GetPositionRequest
	(*PositionInfo)(nil),            // 5: swap.PositionInfo
	(*PositionResponse)(nil),        // 6: swap.PositionResponse
	(*GetCurrentOrderRequest)(nil),  // 7: swap.GetCurrentOrderRequest
	(*OrderInfo)(nil),               // 8: swap.OrderInfo
	(*CurrentOrderResponse)(nil),    // 9: swap.CurrentOrderResponse
	(*GetHistoryOrderRequest)(nil),  // 10: swap.GetHistoryOrderRequest
	(*HistoryOrderResponse)(nil),    // 11: swap.HistoryOrderResponse
	(*GetLeverageRequest)(nil),      // 12: swap.GetLeverageRequest
	(*LeverageResponse)(nil),        // 13: swap.LeverageResponse
	(*AddOrderRequest)(nil),         // 14: swap.AddOrderRequest
	(*AddOrderResponse)(nil),        // 15: swap.AddOrderResponse
	(*CancelOrderRequest)(nil),      // 16: swap.CancelOrderRequest
	(*CancelOrderResponse)(nil),     // 17: swap.CancelOrderResponse
	(*QuickCloseRequest)(nil),       // 18: swap.QuickCloseRequest
	(*QuickCloseResponse)(nil),      // 19: swap.QuickCloseResponse
	(*GetWalletRequest)(nil),        // 20: swap.GetWalletRequest
	(*WalletInfo)(nil),              // 21: swap.WalletInfo
	(*GetWalletResponse)(nil),       // 22: swap.GetWalletResponse
	(*TransferRequest)(nil),         // 23: swap.TransferRequest
	(*TransferResponse)(nil),        // 24: swap.TransferResponse
	(*GetTransactionsRequest)(nil),  // 25: swap.GetTransactionsRequest
	(*TransactionInfo)(nil),         // 26: swap.TransactionInfo
	(*GetTransactionsResponse)(nil), // 27: swap.GetTransactionsResponse
}
var file_swap_proto_depIdxs = []int32{
	1,  // 0: swap.ContractListResponse.list:type_name -> swap.ContractInfoResponse
	5,  // 1: swap.PositionResponse.list:type_name -> swap.PositionInfo
	8,  // 2: swap.CurrentOrderResponse.list:type_name -> swap.OrderInfo
	8,  // 3: swap.HistoryOrderResponse.list:type_name -> swap.OrderInfo
	21, // 4: swap.GetWalletResponse.wallet:type_name -> swap.WalletInfo
	26, // 5: swap.GetTransactionsResponse.list:type_name -> swap.TransactionInfo
	0,  // 6: swap.SwapService.GetContractInfo:input_type -> swap.GetContractInfoRequest
	2,  // 7: swap.SwapService.GetContractList:input_type -> swap.GetContractListRequest
	4,  // 8: swap.SwapService.GetPosition:input_type -> swap.GetPositionRequest
	7,  // 9: swap.SwapService.GetCurrentOrder:input_type -> swap.GetCurrentOrderRequest
	10, // 10: swap.SwapService.GetHistoryOrder:input_type -> swap.GetHistoryOrderRequest
	12, // 11: swap.SwapService.GetLeverage:input_type -> swap.GetLeverageRequest
	14, // 12: swap.OrderEntrustService.AddOrder:input_type -> swap.AddOrderRequest
	16, // 13: swap.OrderEntrustService.CancelOrder:input_type -> swap.CancelOrderRequest
	18, // 14: swap.OrderEntrustService.QuickClose:input_type -> swap.QuickCloseRequest
	20, // 15: swap.ContractWalletService.GetWallet:input_type -> swap.GetWalletRequest
	23, // 16: swap.ContractWalletService.Transfer:input_type -> swap.TransferRequest
	25, // 17: swap.ContractWalletService.GetTransactions:input_type -> swap.GetTransactionsRequest
	1,  // 18: swap.SwapService.GetContractInfo:output_type -> swap.ContractInfoResponse
	3,  // 19: swap.SwapService.GetContractList:output_type -> swap.ContractListResponse
	6,  // 20: swap.SwapService.GetPosition:output_type -> swap.PositionResponse
	9,  // 21: swap.SwapService.GetCurrentOrder:output_type -> swap.CurrentOrderResponse
	11, // 22: swap.SwapService.GetHistoryOrder:output_type -> swap.HistoryOrderResponse
	13, // 23: swap.SwapService.GetLeverage:output_type -> swap.LeverageResponse
	15, // 24: swap.OrderEntrustService.AddOrder:output_type -> swap.AddOrderResponse
	17, // 25: swap.OrderEntrustService.CancelOrder:output_type -> swap.CancelOrderResponse
	19, // 26: swap.OrderEntrustService.QuickClose:output_type -> swap.QuickCloseResponse
	22, // 27: swap.ContractWalletService.GetWallet:output_type -> swap.GetWalletResponse
	24, // 28: swap.ContractWalletService.Transfer:output_type -> swap.TransferResponse
	27, // 29: swap.ContractWalletService.GetTransactions:output_type -> swap.GetTransactionsResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_swap_proto_init() }
func file_swap_proto_init() {
	if File_swap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swap_proto_rawDesc), len(file_swap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_swap_proto_goTypes,
		DependencyIndexes: file_swap_proto_depIdxs,
		MessageInfos:      file_swap_proto_msgTypes,
	}.Build()
	File_swap_proto = out.File
	file_swap_proto_goTypes = nil
	file_swap_proto_depIdxs = nil
}
